apiVersion: v1
kind: Service
metadata:
  name: ekart-website-service
spec:
  type: LoadBalancer # This is what tells AWS to create an internet-facing Load Balancer
  selector:
    app: ekart-website # This must match the 'app' label in your deployment.yaml
  ports:
  - protocol: TCP
    port: 80        # The port the world will access
    targetPort: 80  # The port on your container (from deployment.yaml)
